image: alpine:3.15

variables:
  DOCKER_DRIVER: overlay2
  # DOCKER_HOST: tcp://localhost:2375

stages:
  - DockerRelease

.docker-cli: &docker-cli
  image: docker:git
  services:
    - docker:dind
  cache: {}
  variables:
    IMAGE_NAME: "node"
    AKS_CLUSTER: ""
    RESOURCE_GROUP: ""
  before_script:
    - docker info
    - git fetch --tags -f
    - docker images | grep $CI_REGISTRY_IMAGE | awk '{print $1 ":" $2}' | xargs -n 1 docker rmi
    - REGISTRY_IMAGE=$CI_REGISTRY_IMAGE IMAGE_VERSION=$(git tag --points-at `git rev-list --tags --max-count=1` | grep -E "[0-9]+\.[0-9]+\.[0-9]+") ./_gen-dockerfile.sh
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - >-
      docker build
      $(git tag --points-at `git rev-list --tags --max-count=1` | awk ' { print " -t " ENVIRON["CI_REGISTRY_IMAGE"] ":" $0} ')
      -f dist/Dockerfile
      .
    - >-
      docker build
      $(git tag --points-at `git rev-list --tags --max-count=1` | awk ' { print " -t " ENVIRON["CI_REGISTRY_IMAGE"] ":" $0 "-builder"} ')
      -f dist/Dockerfile.builder
      .

Docker:Build:
  <<: *docker-cli
  stage: DockerRelease
  only:
    - main
  script:
    - docker images

Docker:Build and Release:
  <<: *docker-cli
  stage: DockerRelease
  only:
    - release
    - release-pre-lts
  script:
    - docker images
    - docker push $CI_REGISTRY_IMAGE --all-tags
